name: Deploy to Bluehost

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files to Bluehost via SSH
        uses: easingthemes/ssh-deploy@v4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote-user: bdxabfmy
          remote-host: 162.241.224.161
          remote-path: "/home2/bdxabfmy/public_html"
          local-path: "./"
          args: "-rlgoDzvcO --delete"
          exclude: ".git/, .github/"
